// Cadenas comunes del layout por idioma. Las páginas declaran `lang` en su
// frontmatter (es por defecto) y el layout elige el bloque correspondiente.
module.exports = {
  es: {
    ogLocale: "es_ES",
    skip: "Saltar al contenido",
    schemaDesc: "Consultora de automatización de procesos con inteligencia artificial. Agentes de IA con supervisión humana para empresas de cualquier tamaño y sector.",
    nav: { proceso: "Proceso", sectores: "Sectores", guias: "Guías", noticias: "Noticias", cta: "Agendar llamada" },
    temaTitulo: "Cambiar tema",
    temaOscuro: "Oscuro",
    temaClaro: "Claro",
    stickyCta: "Agendar auditoría →",
    footer: {
      brand: "Agentes de IA que se ocupan de lo mecánico y devuelven tiempo a las personas. Siempre con supervisión humana.",
      empresa: "Empresa",
      comoTrabajamos: "Cómo trabajamos",
      sectores: "Sectores",
      guias: "Guías",
      noticias: "Noticias",
      contacto: "Contacto",
      legal: "Legal",
      privacidad: "Privacidad",
      cookies: "Cookies",
      avisoLegal: "Aviso legal",
    },
    cookiesUi: {
      label: "Aviso de cookies",
      aviso: "Usamos cookies de analítica (Google Analytics) para entender cómo se usa la web y mejorarla. Solo se activan si las aceptas.",
      masInfo: "Más información",
      rechazar: "Rechazar",
      aceptar: "Aceptar",
      gestionar: "Gestionar cookies",
    },
  },
  en: {
    ogLocale: "en_US",
    skip: "Skip to content",
    schemaDesc: "AI process automation consultancy. AI agents with human oversight for companies of any size and sector.",
    nav: { proceso: "Process", sectores: "Sectors", guias: "Guides", noticias: "News", cta: "Book a call" },
    temaTitulo: "Switch theme",
    temaOscuro: "Dark",
    temaClaro: "Light",
    stickyCta: "Book an audit →",
    footer: {
      brand: "AI agents that take on the mechanical work and give people their time back. Always with human oversight.",
      empresa: "Company",
      comoTrabajamos: "How we work",
      sectores: "Sectors",
      guias: "Guides",
      noticias: "News",
      contacto: "Contact",
      legal: "Legal",
      privacidad: "Privacy",
      cookies: "Cookies",
      avisoLegal: "Legal notice",
    },
    cookiesUi: {
      label: "Cookie notice",
      aviso: "We use analytics cookies (Google Analytics) to understand how the site is used and improve it. They are only activated if you accept them.",
      masInfo: "More information",
      rechazar: "Reject",
      aceptar: "Accept",
      gestionar: "Manage cookies",
    },
  },
  pt: {
    htmlLang: "pt-PT",
    ogLocale: "pt_PT",
    skip: "Saltar para o conteúdo",
    schemaDesc: "Consultora de automatização de processos com inteligência artificial. Agentes de IA com supervisão humana para empresas de qualquer dimensão e setor.",
    nav: { proceso: "Processo", sectores: "Setores", guias: "Guias", noticias: "Notícias", cta: "Agendar chamada" },
    temaTitulo: "Mudar tema",
    temaOscuro: "Escuro",
    temaClaro: "Claro",
    stickyCta: "Agendar auditoria →",
    footer: {
      brand: "Agentes de IA que assumem o trabalho mecânico e devolvem tempo às pessoas. Sempre com supervisão humana.",
      empresa: "Empresa",
      comoTrabajamos: "Como trabalhamos",
      sectores: "Setores",
      guias: "Guias",
      noticias: "Notícias",
      contacto: "Contacto",
      legal: "Legal",
      privacidad: "Privacidade",
      cookies: "Cookies",
      avisoLegal: "Aviso legal",
    },
    cookiesUi: {
      label: "Aviso de cookies",
      aviso: "Usamos cookies de análise (Google Analytics) para perceber como o site é utilizado e melhorá-lo. Só são ativadas se as aceitar.",
      masInfo: "Mais informação",
      rechazar: "Rejeitar",
      aceptar: "Aceitar",
      gestionar: "Gerir cookies",
    },
  },
};
